In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("..\dataDumper.parquet")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\natha\AppData\Local\Temp\ipykernel_10640\1825081457.py:1: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_parquet("..\dataDumper.parquet")

In [3]:
df.head(3)

,Time_utc,VehicleName,VehicleType,Pressure_Pa_1,Pressure_Pa_2,Pressure_Pa_3,Pressure_Pa_4,Pressure_Pa_5,Pressure_Pa_6,Temperature_K_1,...,Altitude_m,Speed_mps,epsilonX,epsilonY,epsilonZ,epsilonSpeed,AtmosphericPressure_Pa,dt_s,dd_m,RatioPayload
0,2023-01-01 00:00:00.328,C-132,Dumper,993010.933333,1.003995e+06,856000.0,798005.466667,819994.533333,864994.533333,346.15,...,4581.000000,9.003,6.207,6.312,23.000000,0.0,59002.557667,4.912,41.480140,0.0
1,2023-01-01 00:00:05.338,C-132,Dumper,993177.933329,1.003911e+06,856000.0,798088.966665,819911.033335,864911.033335,346.15,...,4577.600098,9.003,6.393,6.797,27.600000,0.0,59028.296172,5.010,45.952211,0.0
2,2023-01-01 00:00:10.331,C-132,Dumper,993344.366669,1.003828e+06,856000.0,798172.183334,819827.816666,864827.816666,346.15,...,4573.000000,9.723,6.721,7.631,32.200001,0.0,59064.789917,4.993,47.007842,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201312 entries, 0 to 201311
Data columns (total 33 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Time_utc                201312 non-null  object
 1   VehicleName             201312 non-null  object
 2   VehicleType             201312 non-null  object
 3   Pressure_Pa_1           198245 non-null  float64
 4   Pressure_Pa_2           201106 non-null  float64
 5   Pressure_Pa_3           201190 non-null  float64
 6   Pressure_Pa_4           201088 non-null  float64
 7   Pressure_Pa_5           201178 non-null  float64
 8   Pressure_Pa_6           201158 non-null  float64
 9   Temperature_K_1         198245 non-null  float64
 10  Temperature_K_2         201106 non-null  float64
 11  Temperature_K_3         201190 non-null  float64
 12  Temperature_K_4         201088 non-null  float64
 13  Temperature_K_5         201178 non-null  float64
 14  Temperature_K_6         201158 non-null  float64
 15  ColdPressure_Pa_1       198245 non-null  float64
 16  ColdPressure_Pa_2       201106 non-null  float64
 17  ColdPressure_Pa_3       201190 non-null  float64
 18  ColdPressure_Pa_4       201088 non-null  float64
 19  ColdPressure_Pa_5       201178 non-null  float64
 20  ColdPressure_Pa_6       201158 non-null  float64
 21  Latitude_dd             201312 non-null  float64
 22  Longitude_dd            201312 non-null  float64
 23  Altitude_m              201312 non-null  float64
 24  Speed_mps               201312 non-null  float64
 25  epsilonX                201312 non-null  float64
 26  epsilonY                201312 non-null  float64
 27  epsilonZ                201312 non-null  float64
 28  epsilonSpeed            201312 non-null  float64
 29  AtmosphericPressure_Pa  200355 non-null  float64
 30  dt_s                    201312 non-null  float64
 31  dd_m                    198678 non-null  float64
 32  RatioPayload            201310 non-null  float64
dtypes: float64(30), object(3)
memory usage: 50.7+ MB

In [5]:
df.isna().any()

Time_utc                  False
VehicleName               False
VehicleType               False
Pressure_Pa_1              True
Pressure_Pa_2              True
Pressure_Pa_3              True
Pressure_Pa_4              True
Pressure_Pa_5              True
Pressure_Pa_6              True
Temperature_K_1            True
Temperature_K_2            True
Temperature_K_3            True
Temperature_K_4            True
Temperature_K_5            True
Temperature_K_6            True
ColdPressure_Pa_1          True
ColdPressure_Pa_2          True
ColdPressure_Pa_3          True
ColdPressure_Pa_4          True
ColdPressure_Pa_5          True
ColdPressure_Pa_6          True
Latitude_dd               False
Longitude_dd              False
Altitude_m                False
Speed_mps                 False
epsilonX                  False
epsilonY                  False
epsilonZ                  False
epsilonSpeed              False
AtmosphericPressure_Pa     True
dt_s                      False
dd_m                       True
RatioPayload               True
dtype: bool

In [6]:
na_counts = df.isna().sum()
na_percent = ((na_counts / len(df)) * 100).round(2)
na_summary = pd.DataFrame({
    'na_count': na_counts,
    'na_percent': na_percent
}).sort_values('na_count', ascending=False)

na_summary

                        na_count  na_percent
Pressure_Pa_1               3067        1.52
ColdPressure_Pa_1           3067        1.52
Temperature_K_1             3067        1.52
dd_m                        2634        1.31
AtmosphericPressure_Pa       957        0.48
Temperature_K_4              224        0.11
ColdPressure_Pa_4            224        0.11
Pressure_Pa_4                224        0.11
Pressure_Pa_2                206        0.10
ColdPressure_Pa_2            206        0.10
Temperature_K_2              206        0.10
ColdPressure_Pa_6            154        0.08
Pressure_Pa_6                154        0.08
Temperature_K_6              154        0.08
ColdPressure_Pa_5            134        0.07
Temperature_K_5              134        0.07
Pressure_Pa_5                134        0.07
Temperature_K_3              122        0.06
ColdPressure_Pa_3            122        0.06
Pressure_Pa_3                122        0.06
RatioPayload                   2        0.00
Time_utc                       0        0.00
VehicleType                    0        0.00
VehicleName                    0        0.00
Latitude_dd                    0        0.00
Speed_mps                      0        0.00
Altitude_m                     0        0.00
Longitude_dd                   0        0.00
epsilonX                       0        0.00
epsilonSpeed                   0        0.00
epsilonZ                       0        0.00
epsilonY                       0        0.00
dt_s                           0        0.00

We note that for each tire, the 3 evaluated variables (temperature, pressure and cold pressure) have the same number of missing values.  
This probably means that these missing values are caused by issues associated with the tire sensors.