In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# import other libraries when needed
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load raw data
df = pd.read_parquet("..\dataDumper.parquet")

In [3]:
df[['phaseNb']] = df[['RatioPayload']].diff().abs().cumsum()

In [4]:
dt_s_tolerance = 0.5
original_dt_s = 5
df["missing_record"] = False
df.loc[(df["dt_s"] - original_dt_s).abs() > dt_s_tolerance, "missing_record"] = True
df["missing_record"] = df["missing_record"].shift(-1)

In [5]:
tire_nb = [6]
tire_columns_to_keep = [
    col
    for tire in tire_nb
    for col in [f"Pressure_Pa_{tire}", f"Temperature_K_{tire}", f"ColdPressure_Pa_{tire}"]
]
columns_to_keep = tire_columns_to_keep + ["missing_record", "phaseNb"]
filtered_df = df[columns_to_keep]

In [6]:
# Sélection des lignes avec au moins une valeur manquante
na_values_df = (
    filtered_df[filtered_df[tire_columns_to_keep].isna().any(axis=1)]
    .drop(columns=tire_columns_to_keep)
)

# Calcul de la différence d'index
index_series = na_values_df.index.to_series()
na_values_df["index_diff"] = index_series.shift(-1) - index_series

# Lignes correspondant à la fin d'une suite d'index consécutifs
end_of_sequence = na_values_df[na_values_df["index_diff"] > 1]
end_of_sequence

       missing_record  phaseNb  index_diff
9116             True     28.0     25301.0
34420            True     65.0      3920.0
38347            True     76.0     21207.0
59565            True    112.0       434.0
59999            True    114.0      5585.0
65592            True    132.0     21718.0
87323            True    204.0      1462.0
88809           False    212.0        28.0
88838            True    212.0     10136.0
98988           False    248.0      6140.0
105134          False    258.0      4466.0
109606           True    274.0      6111.0
115727          False    298.0     17738.0
133473           True    332.0     23695.0
157173           True    372.0      8913.0
166089           True    410.0      4880.0
170974           True    426.0      6782.0

In [7]:
~end_of_sequence["missing_record"]

9116      -2
34420     -2
38347     -2
59565     -2
59999     -2
65592     -2
87323     -2
88809     -1
88838     -2
98988     -1
105134    -1
109606    -2
115727    -1
133473    -2
157173    -2
166089    -2
170974    -2
Name: missing_record, dtype: object

In [8]:
print(f"Columns: {tire_columns_to_keep}")

print(
    f"Number of records with at least one missing value : "
    f"{len(end_of_sequence)}"
)

na_value_missing_position = len(end_of_sequence[end_of_sequence["missing_record"]])
print(
    f"Number of records with missing value that precedes missing record: "
    f"{na_value_missing_position}"
)

na_value_without_missing_position = len(end_of_sequence[~end_of_sequence["missing_record"] == -1])
print(
    f"Number of records with missing value that not precedes missing record: "
    f"{na_value_without_missing_position}"
)

Columns: ['Pressure_Pa_6', 'Temperature_K_6', 'ColdPressure_Pa_6']
Number of records with at least one missing value : 17
Number of records with missing value that precedes missing record: 13
Number of records with missing value that not precedes missing record: 4

In [9]:
indexes_to_keep = (end_of_sequence.index).tolist() + (end_of_sequence.index + 1).tolist()
indexes_to_keep.sort()

df.loc[indexes_to_keep]

,Time_utc,VehicleName,VehicleType,Pressure_Pa_1,Pressure_Pa_2,Pressure_Pa_3,Pressure_Pa_4,Pressure_Pa_5,Pressure_Pa_6,Temperature_K_1,...,epsilonX,epsilonY,epsilonZ,epsilonSpeed,AtmosphericPressure_Pa,dt_s,dd_m,RatioPayload,phaseNb,missing_record
9116,2023-01-01 13:17:57.353,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.061000,9.389000,41.400002,0.000000,59241.098324,5.003000e+00,62.058516,0.0,28.0,True
9117,2023-01-01 13:28:49.923,C-132,Dumper,9.790000e+05,986335.899998,842000.000000,786000.000000,806000.000000,848277.350000,340.15,...,11.776000,11.207000,41.400002,0.000000,61976.493133,6.525700e+02,NaN,0.0,28.0,True
34420,2023-01-03 01:23:16.486,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.355000,7.984000,32.200001,0.000000,NaN,5.077000e+00,36.072924,1.0,65.0,True
34421,2023-01-03 01:39:03.266,C-132,Dumper,9.030544e+05,911945.566669,787136.083328,NaN,765000.000000,800054.433331,316.15,...,8.267000,7.970000,27.600000,0.000000,59255.664828,9.467800e+02,NaN,1.0,65.0,False
38347,2023-01-03 11:17:37.285,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.155000,9.194000,23.000000,0.000000,NaN,4.961000e+00,49.997245,0.0,76.0,True
38348,2023-01-03 11:44:07.352,C-132,Dumper,9.626127e+05,963000.000000,824367.600000,756980.266667,795367.600000,832245.066667,333.15,...,15.040000,23.825001,55.200001,0.000000,62996.000000,1.590067e+03,NaN,0.0,76.0,False
59565,2023-01-04 17:52:55.543,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.723000,6.089000,18.400000,0.000000,58772.311781,4.935000e+00,0.000000,0.0,112.0,True
59566,2023-01-04 23:47:17.033,C-132,Dumper,8.560000e+05,NaN,751000.000000,683000.000000,718000.000000,761716.116668,289.15,...,9.703000,9.361000,27.600000,0.000000,58707.533468,1.672876e+09,NaN,NaN,NaN,False
59999,2023-01-05 01:17:04.185,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.522000,7.644000,27.600000,0.000000,NaN,2.484965e+03,NaN,0.0,114.0,True
60000,2023-01-05 01:51:05.000,C-132,Dumper,9.042500e+05,872250.000000,782916.666667,710833.333333,751833.333333,793833.333333,303.15,...,18.370001,12.357000,64.400002,36.740002,61249.131578,2.040815e+03,NaN,0.0,114.0,True
65592,2023-01-05 11:02:43.420,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.013000,7.163000,23.000000,0.000000,NaN,4.990000e+00,29.361771,0.0,132.0,True
65593,2023-01-05 11:49:46.775,C-132,Dumper,9.841183e+05,947389.791667,839457.083341,753881.666662,806389.791667,847779.583334,329.15,...,11.607000,16.070999,23.000000,0.000000,59220.708192,2.823355e+03,NaN,1.0,133.0,False
87323,2023-01-07 01:31:09.375,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.188000,7.239000,23.000000,0.000000,NaN,4.960000e+00,36.155443,0.0,204.0,True
87324,2023-01-07 01:58:57.000,C-132,Dumper,9.959500e+05,963050.000000,842050.000000,749050.000000,809000.000000,850150.000000,333.15,...,12.948000,22.566999,64.400002,45.130001,59901.705257,1.667625e+03,NaN,0.0,204.0,False
88809,2023-01-07 08:11:57.990,C-132,Dumper,9.710000e+05,NaN,816508.374999,NaN,787000.000000,NaN,332.15,...,6.661000,7.932000,27.600000,0.000000,59050.944552,4.990000e+00,0.000000,0.0,212.0,False
88810,2023-01-07 08:12:02.973,C-132,Dumper,9.710000e+05,NaN,816487.612500,729000.000000,787000.000000,822978.764286,332.15,...,8.947000,9.324000,32.200001,0.000000,59054.596027,4.983000e+00,0.000000,0.0,212.0,False
88838,2023-01-07 08:27:48.106,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.119000,6.153000,23.000000,0.000000,59052.863257,5.087000e+00,0.000000,0.0,212.0,True
88839,2023-01-07 10:06:12.285,C-132,Dumper,9.520000e+05,927000.000000,798000.000000,716000.000000,771000.000000,801000.000000,325.15,...,9.485000,8.151000,23.000000,0.000000,NaN,5.904179e+03,NaN,0.0,212.0,False
98988,2023-01-08 05:58:59.926,C-132,Dumper,1.002995e+06,968000.000000,844997.533338,746000.000000,808997.533338,NaN,337.15,...,7.005000,10.899000,23.000000,0.000000,59059.937315,5.031000e+00,26.954929,0.0,248.0,False
98989,2023-01-08 05:59:04.894,C-132,Dumper,1.002837e+06,968081.566669,844938.824998,746000.000000,809081.566669,850000.000000,337.15,...,7.176000,14.065000,23.000000,0.000000,59073.366070,4.968000e+00,23.100286,0.0,248.0,False
105134,2023-01-08 16:57:57.280,C-132,Dumper,NaN,NaN,816238.666667,NaN,779000.000000,NaN,NaN,...,13.066000,9.442000,41.400002,0.000000,NaN,4.994000e+00,27.973245,0.0,258.0,False
105135,2023-01-08 16:58:02.280,C-132,Dumper,NaN,927019.000000,816259.500000,NaN,779000.000000,750000.000000,NaN,...,12.652000,9.308000,41.400002,0.000000,NaN,5.000000e+00,26.280597,0.0,258.0,False
109606,2023-01-09 00:47:30.416,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.046000,7.725000,23.000000,0.000000,NaN,5.038000e+00,48.984824,0.0,274.0,True
109607,2023-01-09 01:00:05.085,C-132,Dumper,9.954915e+05,964457.625001,831169.499998,810915.250001,803169.499998,817084.749999,332.15,...,13.426000,12.205000,41.400002,0.000000,58084.690230,7.546690e+02,NaN,1.0,275.0,True
115727,2023-01-09 11:01:58.892,C-132,Dumper,9.990000e+05,971000.000000,834000.000000,NaN,NaN,NaN,337.15,...,7.099000,12.099000,18.400000,0.000000,59039.371791,4.967000e+00,0.000000,0.0,298.0,False
115728,2023-01-09 11:02:03.888,C-132,Dumper,9.990000e+05,971032.400000,834000.000000,812000.000000,806000.000000,828000.000000,337.15,...,7.114000,12.210000,18.400000,0.000000,59039.017367,4.996000e+00,0.000000,0.0,298.0,False
133473,2023-01-10 14:46:43.298,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.599000,16.934000,50.599998,33.869999,NaN,4.994000e+00,58.244493,0.0,332.0,True
133474,2023-01-10 15:11:49.358,C-132,Dumper,9.638226e+05,941354.733329,819467.900006,787177.366665,790177.366665,811607.544445,326.15,...,12.159000,12.601000,27.600000,0.000000,59626.678147,1.506060e+03,NaN,0.0,332.0,True
157173,2023-01-12 02:37:48.243,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.915000,12.153000,36.799999,0.000000,NaN,5.011000e+00,47.801620,0.0,372.0,True
157174,2023-01-12 03:17:51.628,C-132,Dumper,1.008279e+06,972558.133333,852441.866667,808441.866667,829569.766667,846860.466667,339.15,...,10.913000,11.065000,27.600000,0.000000,59173.418631,2.403385e+03,NaN,1.0,373.0,False
166089,2023-01-12 17:05:25.265,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.981000,9.016000,32.200001,0.000000,NaN,5.004000e+00,39.561827,0.0,410.0,True
166090,2023-01-12 17:21:40.000,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,853666.666667,NaN,...,15.977000,12.495000,46.000000,31.670000,NaN,9.747350e+02,NaN,1.0,411.0,False
170974,2023-01-13 00:36:29.462,C-132,Dumper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.832000,8.089000,27.600000,0.000000,59850.241250,4.997000e+00,58.151025,0.0,426.0,True
170975,2023-01-13 01:15:14.829,C-132,Dumper,1.021259e+06,996011.400004,865494.299998,812505.700002,840764.250005,862752.850001,343.15,...,23.218000,14.747000,46.000000,0.000000,59234.889561,2.325367e+03,NaN,1.0,427.0,False

In [10]:
df2[df2["missing_value_tire"]]

NameError: name 'df2' is not defined

In [ ]:
df2["missing_value_tire"] & (~df2["missing_record"])

0         False
1         False
2         False
3         False
4         False
          ...
201307    False
201308    False
201309    False
201310    False
201311    False
Length: 201312, dtype: bool